spring:
  application:
    name: "UniversityManagementSystem"

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:dcbapp
    username: sa
    password: password

  jpa:
    hibernate:
      ddl-auto: none

  main:
    web-application-type: none

  sql:
    init:
      mode: always